# Site Settings
title: GDK Site
description: "A description of my awesome website"

# URL Settings (Crucial for GitHub Pages)
url: "https://aden-tt.github.io"
baseurl: "/gdk-site"

# Build Settings
markdown: kramdown
theme: jekyll-theme-primer

# Plugins allowed by GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
